### ISSUE TITLE
Enable feature flags for Econ and Stats

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1825]
@helenemccarron commented on [Fri Aug 10 2018](https://github.com/Connexions/cnx-recipes/issues/537)

## https://github.com/Connexions/cnx-recipes/blob/katAW.petty.pegasus/FEATURES.md

**up-footnote-call**: issue #473
- [ ] tested in econ
- [ ] tested in stats

**trash-empty-table-captions**: issue #434
- [ ] tested in econ
- [ ] tested in stats

**exercise-container**: issue #454
- [ ] tested in econ
- [ ] tested in stats

**delete-link-in-equation-number**: issue #521
- [ ] tested in econ
- [ ] tested in stats

**$Config_TableSummariesAreCaptions**: issue #407
- [ ] tested in econ
- [ ] tested in stats

**$Config_PrefaceHasCaptions**: issue #455
- [ ] tested in econ
- [ ] tested in stats
