### ISSUE TITLE
Review card for 2018-08-27 CNX Release

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1830]
## Dates
- Code freeze (no new features):  **2018-08-16**
- Code deployed to staging server: 2018-08-17
- Testing on staging server: 2018-08-20 => 2018-08-24
- RC Review meeting: 2018-08-21
- Code Released to Production: **2018-08-27**

## Versions:
- oer.exports v0.61.0 (petty.pegasus)
- webview v0.35.0 (petty.pegasus)
- cnx-recipes v1.13.0 (petty.pegasus)
- products.rhaptosprint v0.129
- cnx-archive v4.2.1
- cnx-db v.2.3.2
- cnx-publishing v0.13.0
- cnx-deploy ? (SEO, cache control)

## Demo
- Allow unicode characters in URLs #1813
- weighted search (faster search): https://github.com/Connexions/cnx-db/issues/136

## No Demo
- the rest of 'em

## Repo Checklist (Books+CNX)
<details>
<summary>Click here to see full checklist</summary>

- [x] **oer.exports** (*Helene*)
	- [x] https://github.com/Connexions/oer.exports/blob/master/version.txt should match current release
	- [x] Release created in https://github.com/Connexions/oer.exports/releases
	- [x] New RhaptosPrint egg should be built by DevOps (they need the version number)
- [x] **cnx-recipes** (*Helene*)
	- [x] Release created in https://github.com/Connexions/cnx-recipes/releases
	- [x] PyPi version revved
	- [x] cnx-deploy: `environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [x] **webview** (*Helene*)
 	- [x] Release created in https://github.com/Connexions/webview/releases
	- [x] Tarball for version needs to be available at https://packages.cnx.org/js-builds/ (I think Jenkins builds this automatically?)
	- [x] cnx-deploy: needs a manual PR opened, reviewed, and merged to update `environments/__prod_envs/vars/versions.yml`
- [x] **cnx-archive** (*Ross or Mulich*)
 	- [x] Release tag created in GitHub
 	- [x] PyPi version revved
	- [x] cnx-deploy: 2 files updated: `environments/__prod_envs/files/archive-requirements.txt` and`environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [x] **cnx-db** (*Ross or Mulich*)
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
	- [x] cnx-deploy: 3 files should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [x] **cnx-publishing** (*Ross or Mulich*)
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
	- [x] cnx-deploy: `environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
</details>

## Links to DevOps cards:
- [staging](https://trello.com/c/cDK4EVXk/231-cnxbooks-deploy-to-staging-servers-for-20180827-release)
- [prod](https://trello.com/c/lnVjFd4L)

**Comment by kerwinso** [comment]
Ross revved cnx-db to 2.3.2 and cnx-deploy to 2.25.1 on Mon 8/20.

**Comment by kerwinso** [comment]
cnx-archive revved to 4.2.1
